name: calories_remake
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.0.1
  google_nav_bar: ^5.0.6
  page_transition: ^2.1.0
  intl: ^0.19.0
  http: ^1.2.2
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  provider:
  flutter_localizations:
    sdk: flutter
  flutter_locales:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/backgroudLogin.png
    - assets/ForgotPasswordImg.png
    - assets/huh_cat.jpg
    - assets/light_mode.png
    - assets/dark_mode.png
    - assets/CaloBurn.png
    - assets/meditation2.png
    - assets/musclee.png
    - assets/df.png
    - assets/balanceBody.png
    - assets/amico.png
    - assets/tyleBMI.png
