import 'package:flutter/material.dart';
Map<String,String> _vi={
  "welcome": "Chào mừng bạn đến với Calories tracker",
  "typeEmail": "Nhập email của bạn",
  "typePassword": "Mật khẩu",
  "typePassword2": "Xác thực mật khẩu",
  "btnLogin": "Đăng nhập",
  "btnSignUp": "Đăng ký",
  "forgotPw": "Quên mật khẩu",
  "anotherType": "    hoặc đăng nhập với    ",
  "backSignIn": "    hoặc đăng ký với    ",
  "quesForSignUp": "Bạn chưa có tài khoản?",
  "signupNow": "Đăng ký ngay",
  "signupText": "Đăng ký",
  "signinText": "Đăng nhập",
  "textSignUp": "Nhập các thông tin bên dưới để tạo tài khoản",
  "userN": "Họ và tên",
  "signinNow": "Bạn đã có tài khoản?",
  "forgotPWtext": "Quên mật khẩu",
  "forgotPWtext2": "Nhập địa chỉ email liên kết\n với tài khoản này",
  "switchAcc":"Đổi tài khoản",
  "profile":"Thông tin cá nhân",
  "forgotPWbtn": "Gửi",
  "questionText1":"Mục tiêu của bạn là gì?",
  "questionText2":"Bạn bao nhiêu tuổi?",
  "questionText3":"Bạn cao bao nhiêu?",
  "questionText3":"Cân nặng gần đây nhất của bạn là bao nhiêu?",
  "subText1": "Chọn tất cả những gì phù hợp",
  "subText2": "Điều này giúp chúng tôi tạo kế hoạch cá nhân hóa cho bạn",
  "subText3": "Điều này giúp chúng tôi tạo kế hoạch cá nhân hóa cho bạn",
  "subText4": "Bạn có thể cập nhật cân nặng của mình bất cứ lúc nào",
  "textGoal1":"Tăng cân",
  "textGoal2":"Giảm cân",
  "textGoal3":"Khỏe mạnh hơn",
  "textGoal4":"Duy trì cân nặng",

};
Map<String,String> _en={
  "welcome": "Welcome to Calories tracker",
  "typeEmail": "Enter your email",
  "typePassword": "Password",
  "typePassword2": "Verify Password",
  "btnLogin": "Login",
  "btnSignUp": "Sign up",
  "forgotPw": "Forgot password",
  "anotherType": "    or Log in with    ",
  "backSignIn": "    or Sign in with    ",
  "quesForSignUp": "Dont have an account?",
  "signupNow": "Sign up",
  "signupText": "Sign up",
  "signinText": "Login",
  "textSignUp": "Fill the details & create your account",
  "userN": "Full name",
  "signinNow": "Already have an account?",
  "forgotPWtext": "Forgot Password",
  "forgotPWtext2": "Enter the email address associated\n with this account",
  "switchAcc":"Switch Account",
  "profile":"Profile",
  "forgotPWbtn": "Send",
  "questionText1":"What are your goals?",
  "questionText2":"How old are you?",
  "questionText3":"How tall are you?",
  "questionText3":"What is your latest weight?",
  "subText1": "Select all that apply",
  "subText2": "This help us create your personalized plan",
  "subText3": "This help us create your personalized plan",
  "subText4": "You can update your weight anytime",
  "textGoal1":"Build Muscle",
  "textGoal2":"Lose Weight",
  "textGoal3":"Be Healthier",
  "textGoal4":"Balance Body",


};
String currentLang = "vi";
String lang(String key, String defaultString ){
  if(currentLang=="en")return _en[key]??defaultString;
  return _vi[key]??defaultString;
}
